services:
  # Banco de dados PostgreSQL
  postgres:
    image: postgres:15
    container_name: hubdosaber-postgres
    environment:
      POSTGRES_DB: hubdosaber_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hubdosaber-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Aplicação Spring Boot
  app:
    build: .
    container_name: hubdosaber-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/hubdosaber_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - hubdosaber-network

volumes:
  postgres_data:

networks:
  hubdosaber-network:
    driver: bridge
