CREATE TABLE city
(
    id    INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255),
    state VARCHAR(255),
    CONSTRAINT pk_city PRIMARY KEY (id)
);

CREATE TABLE university
(
    id      UUID NOT NULL,
    name    VARCHAR(255),
    acronym VARCHAR(255),
    CONSTRAINT pk_university PRIMARY KEY (id)
);

CREATE TABLE users
(
    id            UUID         NOT NULL,
    matriculation VARCHAR(255) NOT NULL,
    password      VARCHAR(255) NOT NULL,
    name          VARCHAR(255) NOT NULL,
    email         VARCHAR(255) NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_matriculation UNIQUE (matriculation);